feat: add timeouts to loading overlay [#142] (#144)
* feat: add timeouts to loading overlay [#142]

* fix: remove unnecessary logging import [#142]

* fix: add tests [#142]

* fix: ensure overlay count can't go below zero [#142]

* fix: pr changes

* fix: add test report to automation

---------

Co-authored-by: Simon Lightfoot <simon@devangels.london>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -52,5 +52,17 @@ jobs:
           echo $TEST_ENV_BASE64 | base64 --decode > packages/clerk_auth/.env.test
 
       - name: Run tests in clerk_auth
-        run: dart test
+        run: dart test --file-reporter=json:../../reports/clerk_auth.json
         working-directory: packages/clerk_auth
+
+      - name: Run tests in clerk_flutter
+        run: flutter test --file-reporter=json:../../reports/clerk_flutter.json
+        working-directory: packages/clerk_flutter
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: 'Test Report'         # Name of the check run which will be created
+          path: reports/*.json        # Path to test results
+          reporter: flutter-json      # Format of test results
